# Generated by Django 6.0.2 on 2026-02-05 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
